### PR TITLE
fix CoinOr to support VS2022

### PR DESCRIPTION
**Pull request by cbielow**
coinOr would target the wrong solution in the tar.gz

New tar.gz is already uploaded.

### CODE REVIEW

**Comment by cbielow** [comment]
CI will fail because the very SHA-1 does not match...
Will merge

**Comment by jpfeuffer** [comment]
Wait. Why will it fail?

**Comment by jpfeuffer** [comment]
Where did you upload the targz?

**Comment by timosachsenberg** [comment]
In thcontrib folder of buildarchive. Did not change the name I got from Chris and overwrote the old file

**Comment by jpfeuffer** [comment]
I think the contrib sources are still at FU

**Comment by jpfeuffer** [comment]
No they are not. But are you all sure that the size needs to triple?

**Comment by jpfeuffer** [comment]
Did you use the correct hashing algorithm to calculate the hash?

**Comment by timosachsenberg** [comment]
File size was about the same compared to the one I overwrote. Hash was provided by Chris.

**Comment by cbielow** [comment]
The size problem seems to be down to `CoinMP-1.8.3-vs22.tar.gz\CoinMP-1.8.3-vs22.tar\CoinMP-1.8.3\CoinMP\MSVisualStudio\v17\x64\` which contains all compiled libraries in Debug and Release mode.
Probably happened during the previous packaging.
Should we remove those? Its 35mb more than necessary, but not the end of the world.

**Comment by jpfeuffer** [comment]
Since we probably have to repackage and/or recalculate hashes, I think it is worth it.

**Comment by cbielow** [comment]
the current state seems stable and builds btw...
The SHA1 is correct
Not sure what caused the failure during CI -- some delay in publishing the file?

**Comment by jpfeuffer** [comment]
Ah ok

**Pull request merged**
