### PR TITLE
Adaptations to allow building with Visual Studio 2017

### PR DESCRIPTION
**Pull request by hendrikweisser**
Note that other changes are also necessary to build successfully with VS 2017; see https://github.com/OpenMS/OpenMS/issues/2693.

### CODE REVIEW

**Comment by hroest** [comment]
why is boost 1.64 needed?

**Comment by jpfeuffer** [comment]
I guess because of the generator used when configuring it. https://github.com/OpenMS/contrib/blob/master/libraries.cmake/boost.cmake#L24

**Comment by jpfeuffer** [comment]
But @hendrikweisser didn't you say, that boost should be build with msvc-14.1. The line that I linked would try msvc-15.0 .

**Comment by jpfeuffer** [comment]
rebuild

**Comment by jpfeuffer** [comment]
rebuild

**Comment by jpfeuffer** [comment]
rebuild

**Comment by jpfeuffer** [comment]
rebuild

**Comment by jpfeuffer** [comment]
WHY does MS always have to change their environment variables and stuff?!

**Comment by jpfeuffer** [comment]
rebuild

**Comment by jpfeuffer** [comment]
rebuild

**Comment by jpfeuffer** [comment]
Have to wait until our IT upgrades CMake.

**Comment by hendrikweisser** [comment]
> why is boost 1.64 needed?

Based on what I've seen, it's the first version with support for VS 2017.

> But @hendrikweisser didn't you say, that boost should be build with msvc-14.1. The line that I linked would try msvc-15.0 .

The numbering is inconsistent; VC 15 and 14.1 both refer to VS 2017. I don't remember setting anything special for Boost, but I may have forgotten.

**Comment by jpfeuffer** [comment]
I see. No worries, let's try.

**Comment by jpfeuffer** [comment]
rebuild

**Comment by jpfeuffer** [comment]
rebuild

**Comment by jpfeuffer** [comment]
rebuild

**Comment by jpfeuffer** [comment]
rebuild

**Comment by jpfeuffer** [comment]
rebuild

**Comment by jpfeuffer** [comment]
Okay! Finally works on all Wins and Macs. We have problems with our docker currently. I will wait for them to test it on linux but I do not expect any problems.

**Pull request merged**
