### PR TITLE
Feature/update eigen

### PR DESCRIPTION
**Pull request by timosachsenberg**
another try of update eigen

### CODE REVIEW

**Comment by hroest** [comment]
great, 3.3.4 is the same as currently in debian testing and unstable (and ubuntu 17.10): https://packages.debian.org/search?keywords=eigen

**Comment by jpfeuffer** [comment]
Ah I activated it only for PRs to develop.

**Comment by timosachsenberg** [comment]
one build failed because of:
Reading state information...
E: Unable to locate package g++-7
E: Couldn't find any package by regex 'g++-7'

**Comment by timosachsenberg** [comment]
so would you recommend merging it now and use it in the release? or should we wait?

**Comment by jpfeuffer** [comment]
Hm yes we could. We would need to update the contrib submodule to the new commit. But beware it might affect tests so it could be that it triggers more changes.
Yes according to Hannes' suggestion I tried gcc7 but I need to include a newer docker images first.

**Comment by timosachsenberg** [comment]
Ok then let’s not include it in the release and merge it so we can use it in develop

**Comment by jpfeuffer** [comment]
Ok I added ubuntu 18.04 with gcc7 to the list. looks good. Needs conflict resolution though.

**Comment by timosachsenberg** [comment]
done lets see if it builds :P

**Pull request merged**
