### PR TITLE
Dockerfiles from OpenMS/dockerfiles have been moved to contrib/docker…

### PR DESCRIPTION
**Pull request by KyowonJeong**
Dockerfiles have been moved under contrib/dockerfiles/

### CODE REVIEW

**Comment by jpfeuffer** [comment]
https://github.com/OpenMS/contrib/blob/master/.github/workflows/deploydocker.yml#L35

Will break

**Comment by jpfeuffer** [comment]
Same for the other workflow

**Comment by timosachsenberg** [comment]
@jpfeuffer can you give @KyowonJeong some hints how to update the action?
How I interpret the linked line:
In the current action it had to check out the Dockerfile from the Dockerfiles repository.
After his PR the Dockerfile is already available right? So this download step is not required, right?

**Comment by jpfeuffer** [comment]
Yes correct

**Comment by jpfeuffer** [comment]
Yes. Ideally also remove the now unnecessary branching logic. But this involves changing the Dockerfile itself.

**Comment by KyowonJeong** [comment]
Oh sure.  Thanks for the comments!! I will correct them and add to pr.

**Comment by KyowonJeong** [comment]
After reading @timosachsenberg 's explanation, I could understand why this part should be removed. Nice. Thanks!

**Comment by jpfeuffer** [comment]
The context in Line 42 of the workflow yml must lastly be changed to point to `dockerfiles` instead of `dockerfiles/contrib` I think

**Comment by KyowonJeong** [comment]
> 

Thanks! Is there a way to test if this works? I am totally ignorant about docker, but a bit of hit would be very helpful.

**Comment by jpfeuffer** [comment]
Oh yes. You actually *have* to change something in that regard.
In the beginning of the action it says: runs on `push:` to certain branches.
In this repository the main branch is called develop, not master. This needs to be changed in the `Define tag name` as well.

And then, while you are at it, you can temporarily change the trigger to also run on the branch you are currently pushing to. `docker_contrib_files_added`

BUT: in the last step, this will publish a docker container to our registry with a tag that corresponds to your branch. This clutters our registry a bit. So maybe you would need to adapt that last step to push only if the branch is develop or release/*

**Comment by timosachsenberg** [comment]
Hi,
Let me break down Julianus comment (and let me know if that is annoying or of any help ;) ). 
You need to
- change the master in push: branches: to develop will trigger the action if something is pushed to develop
- change master in ```if [[ "$BRANCH" == "master" ]]``` to "develop" as well

The other part of his comment deals with how you can temporarily test the action:

- you could add the name of your branch at the appropriate places, so it also runs on it on a push or when triggered through
the manual trigger that allows to run the workflow
image
- but then you might add a check in the upload part of the action that it only publishes the container if on develop or release branch

**Comment by jpfeuffer** [comment]
Thanks. By the way, I think the changes are small enough so we can test them after merge, so testing is optional. I mean the dockerfile was not changed, so it should not fail.

**Comment by KyowonJeong** [comment]
Oh I see. I changed master to develop in two places as you instructed.

And did not touch 'release/**'. so now it seems :


push:
  branches:
    - develop
    - 'release/**'

One question though. Why develop is just develop while release is 'release/**'??


Thanks!


Kyowon

________________________________
보낸 사람: Julianus Pfeuffer ***@***.***>
보낸 날짜: 2023년 2월 16일 목요일 오후 9:51:31
받는 사람: OpenMS/contrib
참조: KyowonJeong; Mention
제목: Re: [OpenMS/contrib] Dockerfiles from OpenMS/dockerfiles have been moved to contrib/docker… (PR #126)


Oh yes. You actually have to change something in that regard.
In the beginning of the action it says: runs on push: to certain branches.
In this repository the main branch is called develop, not master. This needs to be changed in the Define tag name as well.

And then, while you are at it, you can temporarily change the trigger to also run on the branch you are currently pushing to. docker_contrib_files_added

BUT: in the last step, this will publish a docker container to our registry with a tag that corresponds to your branch. This clutters our registry a bit. So maybe you would need to adapt that last step to push only if the branch is develop or release/*

**Comment by KyowonJeong** [comment]
Oh.. I need to study what github action does at some point...

**Comment by jpfeuffer** [comment]
release/* means it is run for any branch starting with release/.

release/2.7, release/2.8, ...

**Comment by timosachsenberg** [comment]
I think it looks good now

**Comment by timosachsenberg** [comment]
the action fails:
https://github.com/OpenMS/contrib/actions/runs/4222935118/jobs/7332051563

see:
Run docker/login-action@v[2](https://github.com/OpenMS/contrib/actions/runs/4222935118/jobs/7332051563#step:6:2)
  with:
    registry: ghcr.io
    username: jpfeuffer
    password: ***
    ecr: auto
    logout: true
Logging into ghcr.io...
Error: Error response from daemon: Get "https://ghcr.io/v2/": denied: denied

@jpfeuffer do you need to enter your credentials to contrib?

**Comment by jpfeuffer** [comment]
Nothing should have changed regarding login. I don't know.
We should find a more sustainable login anyway.

**Comment by jpfeuffer** [comment]
This action was forgotten anyway was not changed at all

**Comment by timosachsenberg** [comment]
ah yeah I see. @KyowonJeong only updated the deploy docker image action.
@KyowonJeong are you available for updating this? otherwise I can take a look at it.

**Pull request merged**
