### PR TITLE
[FEATURE/FIX] Improve support for newer OSX versions and MSVC compilers

### PR DESCRIPTION
**Pull request by jpfeuffer**
It ended up being an update of the two largest libraries (CoinOR and Boost).
Once this PR is stable, I will test the linking to OpenMS seperately and report back.
I was able to remove quite some patches that were needed before.
I tried to include a better support of OSX compatibility mode e.g. using CMAKE_OSX_DEPLOYMENT_TARGET.

### CODE REVIEW

**Comment by jpfeuffer** [comment]
[rebuild]

**Comment by jpfeuffer** [comment]
[rebuild]

**Comment by jpfeuffer** [comment]
[rebuild]

**Comment by jpfeuffer** [comment]
[rebuild]

**Comment by jpfeuffer** [comment]
[rebuild]

**Comment by jpfeuffer** [comment]
[rebuild]

**Comment by jpfeuffer** [comment]
Changes to CI [rebuild]

**Comment by jpfeuffer** [comment]
Okay. Builds on every platform now with no obviously wrongly chosen compilers. I will test the linking now.

**Comment by hroest** [comment]
@jpfeuffer will this work for MSVS2015 ? this would be great as Python 3.5 is using MSVS 2015 and therefore pyopenms for Python 3.5 will require MSVS2015

**Comment by hroest** [comment]
secondly, we have to be careful to not rely on "too new" boost features, as even the newest ubuntu 16.04 has only boost 1.58 https://launchpad.net/ubuntu/xenial/+package/libboost-dev while 14.04 has boost 1.54 and we do want OpenMS to be compatible with current debian/ubuntu/fedora releases (otherwise we make the life of release managers really difficult)

Not sure how to best approach this but we should from time to time try to do a "distro-build" to ensure nobody introduces features that are dependent on recent releases of boost etc

**Comment by jpfeuffer** [comment]
> will this work for MSVS2015 ? this would be great as Python 3.5 is using MSVS 2015 and therefore pyopenms for Python 3.5 will require MSVS2015

We do not yet have MSVS2015 installed and it is therefore not yet tested. But this is on my list.

> secondly, we have to be careful to not rely on "too new" boost features, as even the newest ubuntu 16.04 has only boost 1.58 https://launchpad.net/ubuntu/xenial/+package/libboost-dev while 14.04 has boost 1.54 and we do want OpenMS to be compatible with current debian/ubuntu/fedora releases (otherwise we make the life of release managers really difficult)

That is a good point. I agree with you.

> Not sure how to best approach this but we should from time to time try to do a "distro-build" to ensure nobody introduces features that are dependent on recent releases of boost etc

 I can easily do separate tests with dockerized linux machines that install the contrib via their package managers in a certain interval. But I think that should be separate from this contrib package that provides an easy install of all of the libraries at once and it should not matter which version the libraries have in here, as long as they build on the targeted system right? This repo is for installing the libraries when you can not or do not want to use the package manager right? Or how do you and others see this?

**Comment by jpfeuffer** [comment]
[rebuild] Now with subsequent linking against OpenMS.

**Comment by jpfeuffer** [comment]
[rebuild] Sorry for spamming, CI is still in test phase.

**Comment by jpfeuffer** [comment]
[rebuild] Now with subsequent linking against OpenMS.

**Comment by jpfeuffer** [comment]
[rebuild] Now with subsequent linking against OpenMS.

**Comment by jpfeuffer** [comment]
[rebuild] Now with subsequent linking against OpenMS.

**Comment by jpfeuffer** [comment]
[rebuild]

**Comment by jpfeuffer** [comment]
[rebuild] Now with subsequent linking against OpenMS.

**Comment by jpfeuffer** [comment]
[rebuild] Now with subsequent linking against OpenMS.

**Comment by jpfeuffer** [comment]
[rebuild] Now with subsequent linking against OpenMS.

**Comment by jpfeuffer** [comment]
[rebuild] Now with subsequent linking against OpenMS.

**Comment by jpfeuffer** [comment]
[rebuild] Now with subsequent linking against OpenMS.

**Comment by jpfeuffer** [comment]
[rebuild]

**Comment by jpfeuffer** [comment]
[rebuild]

**Comment by jpfeuffer** [comment]
[rebuild] Now with subsequent linking against OpenMS.

**Comment by jpfeuffer** [comment]
[rebuild] Forgot read permissions.

**Comment by jpfeuffer** [comment]
[rebuild] Forgot read permissions.

**Comment by jpfeuffer** [comment]
Just as a note: MSVC 12 ( from Visual Studio 2013) in Update < 5 had problems with newer Boost versions.

**Comment by jpfeuffer** [comment]
Okay try again [rebuild]

**Comment by jpfeuffer** [comment]
[rebuild] Had to rebase due to hotfix.

**Comment by jpfeuffer** [comment]
[rebuild] Had to rebase due to hotfix.

**Comment by cbielow** [comment]
looks good to me.

Will the new Boost version be backwards compatible with VS2008? Or 2010 at least?

**Comment by jpfeuffer** [comment]
2010 definitely, I could not get a hold on 2008 yet. I am still a bit testing, so please wait for merge.

**Comment by jpfeuffer** [comment]
rebuild

**Comment by jpfeuffer** [comment]
rebuild

**Comment by jpfeuffer** [comment]
rebuild

**Comment by jpfeuffer** [comment]
rebuild

**Comment by jpfeuffer** [comment]
rebuild

**Comment by rrahn** [comment]
Can't set status; build failed.

**Comment by rrahn** [comment]
Can't set status; build failed.

**Comment by rrahn** [comment]
Can't set status; build failed.

**Comment by rrahn** [comment]
Can't set status; build failed.

**Comment by rrahn** [comment]
Can't set status; build failed.

**Comment by rrahn** [comment]
Can't set status; build failed.

**Comment by rrahn** [comment]
Can't set status; build failed.

**Comment by rrahn** [comment]
Can't set status; build failed.

**Comment by jpfeuffer** [comment]
rebuild

**Comment by jpfeuffer** [comment]
rebuild

**Comment by jpfeuffer** [comment]
rebuild

**Comment by jpfeuffer** [comment]
rebuild

**Comment by jpfeuffer** [comment]
rebuild

**Comment by jpfeuffer** [comment]
rebuild

**Comment by jpfeuffer** [comment]
rebuild

**Comment by jpfeuffer** [comment]
rebuild

**Comment by jpfeuffer** [comment]
rebuild

**Comment by jpfeuffer** [comment]
rebuild

**Comment by cbielow** [comment]
can we go ahead and merge this?
We should introduce a Tag (OpenMS 2.1) for this branch before the merge, to indicate that its synced with OpenMS releases.
@hroest: this would ensure that people can still build with VS2008, since it might not be running after this PR

**Comment by hroest** [comment]
anyways we dont know how long we will support MSVS 2008. At least for boost, it seems possible to compile 1.61 with MVS 2008 http://www.npcglib.org/~stathis/blog/precompiled-boost/

My worry is a bit that OpenMS will use features from the new boost and then not compile with older versions any more and that would be an issue for linux packaging as they just have a single version to work with. But the docker solution with regular tests that @jpfeuffer suggested seems like a good idea to me

**Comment by cbielow** [comment]
ok, the tag exists already.
Will merge.

**Comment by hroest** [comment]
@cbielow @jpfeuffer did somebody test OpenMS with the new boost 1.61 ? That may actually be a good idea

**Comment by cbielow** [comment]
it did run through (obviously) :)

I can try again though tomorrow


Am 2/28/2017 um 8:58 PM schrieb Hannes Roest:

**Comment by hroest** [comment]
@cbielow I mean also running all the tests...

**Comment by cbielow** [comment]
I must had another local boost, since using the contrib I get (sorted by source of error):

`RNG errors:`
339 - SvmTheoreticalSpectrumGenerator_test (Failed)
341 - SvmTheoreticalSpectrumGeneratorSet_test (Failed)
509 - MSSim_test (Failed)
512 - RawTandemMSSignalSimulation_test (Failed)

`unclear source of error:`
519 - MRMAssay_test (Failed)
519:     got:      '    <Transition id="UISDECOY_{LHIN(Deamidated)QAR|LHINQ(Deamidated)AR|LHINQAR}_381.6818_123.5817_-39.95_y2^2" peptideRef="1_sp|P0C0L4|CO4A_HUMAN_AAAN(Deamidated)QMR_2_-39.95">'
519:     expected: '    <Transition id="UISDECOY_{NENN(Deamidated)QER|NENNQ(Deamidated)ER|NENNQER}_381.6818_152.5844_-39.95_y2^2" peptideRef="1_sp|P0C0L4|CO4A_HUMAN_AAAN(Deamidated)QMR_2_-39.95">'

        1690 - TOPP_FeatureLinkerUnlabeledQT_5_out1 (Failed)
        1692 - TOPP_FeatureLinkerUnlabeledQT_6_out1 (Failed)
        1705 - TOPP_IDMapper_4 (Failed)
        1706 - TOPP_IDMapper_4_out1 (Failed)
        1707 - TOPP_IDMapper_5 (Failed)
        1708 - TOPP_IDMapper_5_out1 (Failed)
1707: C:\dev\OpenMS\src\openms\source\FORMAT\HANDLERS\XMLHandler.cpp(103): While loading 'C:/dev/OpenMS/src/tests/topp/IDMapper_5_input.idXML': string representation overflows output binary result( in line 4 column 276)
1707: Error: Unable to read file (While loading 'C:/dev/OpenMS/src/tests/topp/IDMapper_5_input.idXML': string representation overflows output binary result( in line 4 column 276) in: C:/dev/OpenMS/src/tests/topp/IDMapper_5_input.idXML)

**Comment by hroest** [comment]
the `FeatureLinkerUnlabeledQT` are probably also RNG errors as its just the ordering of the maps in my case but the files are otherwise identical. Similarly, `MRMAssay` generates randomly shuffled peptides and I suspect its an RNG error

**Pull request merged**
