### PR TITLE
[ADD] set zlib osx deployment target (cmake)

### PR DESCRIPTION
**Pull request by oliveralka**

### CODE REVIEW

**Comment by oliveralka** [comment]
@jpfeuffer Any idea why this is not working in the CI? Ubuntu 20.04?

**Comment by jpfeuffer** [comment]
If I understand the if logic correctly you are trying to build it twice on Linux?
I think I have done that change to other libraries e.g. Xerces. I just declared an Args variable that is empty for Linux. Then you don't even need an if case for the whole command.

**Comment by oliveralka** [comment]
OK, that is much cleaner - thanks a lot.

**Comment by oliveralka** [comment]
I think it is a cmake 3.21.2 issue - worked like a charm locally on macOS/linux with 3.15

**Pull request merged**
