### PR TITLE
[FIX] enable gcc5 support for wildmagic

### PR DESCRIPTION
**Pull request by aiche**

### CODE REVIEW

**Comment by hroest** [comment]
sounds like a good idea :+1:  please merge! 

however, does this also fix the boost issue that we had? or is that just a matter of re-compiling?

**Comment by aiche** [comment]
compiling boost with gcc5 will require some additional steps (pr is coming soon). I manually applied the fix on the build machine to check if it works. http://cdash.openms.de/buildSummary.php?buildid=138978 looks good so I will prepare the additional pr.

**Comment by hroest** [comment]
it looks like something has not really worked: a lot of errors but no build

**Comment by aiche** [comment]
the missing test results seem to be an issue with the upload of the results, I checked the logs directly on the machine and at least the build passed, but following test failures occurred.

```
        549 - TOPPView_test (OTHER_FAULT)
        761 - UTILSWRITEINI_FeatureFinderSuperHirn (SEGFAULT)
        762 - UTILSWRITEINI_FeatureFinderSuperHirn_SectionName (Failed)
        862 - UTILSWRITECTD_FeatureFinderSuperHirn (SEGFAULT)
        1755 - UTILS_FeatureFinderSuperHirn_1 (SEGFAULT)
        1756 - UTILS_FeatureFinderSuperHirn_1_out1 (Failed)
        1757 - UTILS_FeatureFinderSuperHirn_2 (SEGFAULT)
        1758 - UTILS_FeatureFinderSuperHirn_2_out1 (Failed)
```

Lets see if the upload works tomorrow.

**Comment by hroest** [comment]
sounds good

somebody at some point needs to go and debug FFSuperhirn on mac osx. If somebody sends me a backtrace of the segfault, I could debug it

**Comment by aiche** [comment]
looks like there is something going wrong during library init

```
Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_INVALID_ADDRESS at address: 0x0000000000000000
0x0000000100074fad in xercesc_3_1::XMLString::replicate ()
(gdb) bt
#0  0x0000000100074fad in xercesc_3_1::XMLString::replicate ()
#1  0x0000000100094089 in xercesc_3_1::ENameMap::ENameMap ()
#2  0x00000001000946f7 in xercesc_3_1::ENameMapFor<xercesc_3_1::XMLChTranscoder>::ENameMapFor ()
#3  0x0000000101a7b8df in xercesc_3_1::XMLTransService::initTransService ()
#4  0x0000000101a5d083 in xercesc_3_1::XMLPlatformUtils::Initialize ()
#5  0x0000000101492b06 in OpenMS::Internal::XMLFile::parse_ (this=0x7fff5fbfc8b0, filename=@0x7fff5fbfc990, handler=0x7fff5fbfc550) at /Users/??/NIGHTLY/HEAD/src/openms/source/FORMAT/XMLFile.cpp:108
#6  0x000000010145713b in OpenMS::ParamXMLFile::load (this=0x7fff5fbfc8b0, filename=@0x7fff5fbfc990, param=@0x7fff5fbfc920) at /Users/??/NIGHTLY/HEAD/src/openms/source/FORMAT/ParamXMLFile.cpp:366
#7  0x00000001011c07ac in OpenMS::ResidueDB::readResiduesFromFile_ (this=0x105049600, file_name=@0x7fff5fbfcc70) at /Users/??/NIGHTLY/HEAD/src/openms/source/CHEMISTRY/ResidueDB.cpp:194
#8  0x00000001011bf872 in OpenMS::ResidueDB::ResidueDB (this=0x105049600) at /Users/??/NIGHTLY/HEAD/src/openms/source/CHEMISTRY/ResidueDB.cpp:56
#9  0x00000001010d46a7 in OpenMS::ResidueDB::getInstance () at ResidueDB.h:78
#10 0x00000001011d8840 in OpenMS::SvmTheoreticalSpectrumGenerator::initializeMaps_ () at /Users/??/NIGHTLY/HEAD/src/openms/source/CHEMISTRY/SvmTheoreticalSpectrumGenerator.cpp:97
#11 0x00000001011dc529 in OpenMS::SvmTheoreticalSpectrumGenerator::SvmTheoreticalSpectrumGenerator (this=0x1026d5060) at /Users/??/NIGHTLY/HEAD/src/openms/source/CHEMISTRY/SvmTheoreticalSpectrumGenerator.cpp:185
#12 0x00000001011e641d in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at /Users/??/NIGHTLY/HEAD/src/openms/source/CHEMISTRY/SvmTheoreticalSpectrumGenerator.cpp:66
#13 0x00000001011e644d in _GLOBAL__sub_I_SvmTheoreticalSpectrumGenerator.cpp () at /Users/??/NIGHTLY/HEAD/src/openms/source/CHEMISTRY/SvmTheoreticalSpectrumGenerator.cpp:1055
#14 0x00007fff5fc13378 in __dyld__ZN16ImageLoaderMachO18doModInitFunctionsERKN11ImageLoader11LinkContextE ()
#15 0x00007fff5fc13762 in __dyld__ZN16ImageLoaderMachO16doInitializationERKN11ImageLoader11LinkContextE ()
#16 0x00007fff5fc1006e in __dyld__ZN11ImageLoader23recursiveInitializationERKNS_11LinkContextEjRNS_21InitializerTimingListE ()
#17 0x00007fff5fc0ffc4 in __dyld__ZN11ImageLoader23recursiveInitializationERKNS_11LinkContextEjRNS_21InitializerTimingListE ()
#18 0x00007fff5fc0ffc4 in __dyld__ZN11ImageLoader23recursiveInitializationERKNS_11LinkContextEjRNS_21InitializerTimingListE ()
#19 0x00007fff5fc0feba in __dyld__ZN11ImageLoader15runInitializersERKNS_11LinkContextERNS_21InitializerTimingListE ()
#20 0x00007fff5fc01fc0 in __dyld__ZN4dyld24initializeMainExecutableEv ()
#21 0x00007fff5fc05b04 in __dyld__ZN4dyld5_mainEPK12macho_headermiPPKcS5_S5_Pm ()
#22 0x00007fff5fc01397 in __dyld__ZN13dyldbootstrap5startEPK12macho_headeriPPKclS2_Pm ()
#23 0x00007fff5fc0105e in __dyld__dyld_start ()
```

**Comment by aiche** [comment]
boost should be fixed with #11

**Pull request merged**
