### PR TITLE
Update hdf5.cmake to enable h5diff

### PR DESCRIPTION
**Pull request by timosachsenberg**
needed if we want to use the hdf5-config.cmake files.
See discussion at https://github.com/OpenMS/OpenMS/pull/6713

### CODE REVIEW

**Comment by jpfeuffer** [comment]
TBH, the first thing I would have done is probably just updating the version.
I can see someone actually uploaded the sources of the new version already.
https://abibuilder.cs.uni-tuebingen.de/archive/openms/contrib/source_packages/

**Comment by timosachsenberg** [comment]
already use it in my local branch. just pushed the changes here as well

**Comment by jpfeuffer** [comment]
Ah wow, so even the newest version has this potential bug?

**Comment by timosachsenberg** [comment]
I did a force rebuild so I guess yes.
I can try again with everything freshly downloaded just to make sure...

**Comment by jpfeuffer** [comment]
https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_PACKAGE_PREFER_CONFIG.html

Apparently module mode is the default. We should prefer Config whenever available. I think in the case of HDF5 it should be available on all channels (conda, apt, contrib) therefore you could force it with the full signature of find_package:
https://cmake.org/cmake/help/latest/command/find_package.html#full-signature

Try this first before building the tools unnecessarily. The config file actually looks ok.

**Comment by timosachsenberg** [comment]
not needed anymore

**Pull request closed without merging**
