### PR TITLE
use contrib sources from contrib-sources github release

### PR DESCRIPTION
**Pull request by timosachsenberg**
Intend: Move sources away from abibuilder and store on dedicated repo.

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Looks fine to me. Nice idea.

**Comment by cbielow** [comment]
Versioning would be nice to have IMHO.
I.e. tag a contrib release in `contrib-sources` and use that version in `contrib` for download.
Otherwise this will break the build process for older OpenMS releases at some point.

**Comment by timosachsenberg** [comment]
Good point. I am currently having an internal fight how we could do that. 

1. We could do this on demand (otherwise we introduce another process that might not be needed, etc.). If we need to build an old OpenMS version AND the system libraries are not sufficient (e.g., windows), then we create a tag for the old release and need to manually adapt the cmake script.
2. Or go for the cleaner solution and always use tags - but then we really need to make sure that tagging is properly executed on an official release (e.g., needs to go into release script)

Both would be fine I guess because 2 not really happens (ever/a lot?) and might also depend on other stuff like compiler versions etc.

**Comment by cbielow** [comment]
I would simply create a new tag, whenever something in `contrib-sources` changes.
And the contrib script always points to the most recent tag. We should never use `latest`, since this means different things, depending on the time you ask.
This way, there is no need to do anything special during a release. 
And this process should not take a lot of time, since updating contrib sources does not happen very often.

**Comment by timosachsenberg** [comment]
Yes this would be easy.
Just one minor note: the repo does not change anymore. Just releases get added (which allow dropping larger binary files as attachments) which are associated with a tag.

image

How would you do the naming of the contrib-sources? just the date when they got changed?
having version numbers that match the OpenMS ones doesn't make sense in my view or could complicate things

**Comment by timosachsenberg** [comment]
k added the date https://github.com/OpenMS/contrib/commit/b786ca3996192a727fa74eb4df846ce43d3e0e4d

**Pull request merged**
